### ISSUE TITLE
Ignore Properties in CSV

### ISSUE THREAD

**Issue by sonphnt** [damienbod/AspNetCoreCsvImportExport#8]
Hi damienbod,

Thanks for a great library. I have a question:
I have a class with 10 properties. I would like to export to CSV only 5 properties and ignore 5. How could we achieve that?

Something like an attribute on the top of property such as 
[CsvIgnore]
public bool NewProduct {get; set;}

Thanks

**Comment by os1r1s110** [comment]
What could be even nicer is if it could use the same properties as Json.NET? 
Maybe that makes too much assumptions about the user using both Json.Net and this library... but that would make it less verbose on the properties data annotations to specify both the json and the csv ignore/property name

**Comment by os1r1s110** [comment]
I made it work tonight (for the output formatter only for the test I did), will try to provide a PR in the following days that would include both output and input formatters, supporting JsonPropertyAttribute and JsonIgnoreAttribute if you think that could be useful. 

Otherwise, thanks for your library @damienbod , I'll use my edited version of your code in my app :)

**Comment by damienbod** [comment]
@os1r1s110 that would be great, thanks

**Comment by os1r1s110** [comment]
Ok so I did implement it in a pretty basic way but it's working. I'll do the PR tomorrow. 
After talking with @Poke on Slack though, he made me realize that the best option might simply be to use basic DTOs?

I couldn't think of a case where the DTO wouldn't be sufficient to meet the requirements here but maybe there is. 

The option will be there whatsoever if someone needs it.

**Comment by damienbod** [comment]
@os1r1s110 Thanks! 

I will go through this and merge it tody/tomorrow.

**Comment by damienbod** [comment]
merged, thanks
